# -*- coding: utf-8 -*-
"""housing_predictor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JYlx72f6Edx6pQojyc6ugI4jCntnjAK7
"""

import numpy as np
import pandas as pd
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.model_selection import train_test_split
from flask import Flask, request, jsonify,render_template

app = Flask(__name__)

df_cleaned = pd.read_csv(r'D:\D_Drivebkp\tejasdocs\Simplilearn\AVA Technology\Assignments\Data Analytics Part 2 Assignment\Data Analytics Part 2 Assignment\AmesHousing.csv')
df_cleaned.head()

common_fetaures_final = ['Year Built', 'Year Remod/Add', 'Total Bsmt SF', '1st Flr SF', 'Gr Liv Area', 'Garage Area', 'Overall Qual', 'Garage Cars', 'SalePrice']

df_cleaned = df_cleaned[common_fetaures_final].dropna()

df_cleaned.info()

#Split dataset to Train & Test data
X = df_cleaned.drop('SalePrice',axis =1)
Y = df_cleaned['SalePrice']

x_train,x_test,y_train,y_test = train_test_split(X,Y,test_size = 0.3,random_state = 42)

model = GradientBoostingRegressor(random_state = 42)
model.fit(x_train,y_train)


@app.route('/predict',methods = ['Get','POST'])
def index():
  prediction = None
  if request.method == 'POST':
     Year_Built = int(request.form.get('Year_Built'))
     Year_Remod_Add = int(request.form.get('Year_Remod_Add'))
     Total_Bsmt_SF = float(request.form.get('Total_Bsmt_SF'))
     First_Flr_SF =  int(request.form.get('First_Flr_SF'))
     Gr_Liv_Area = int(request.form.get('Gr_Liv_Area'))
     Garage_Area = float(request.form.get('Garage_Area'))
     Overall_Qual =  int(request.form.get('Overall_Qual'))
     Garage_Cars = float(request.form.get('Garage_Cars'))

     User_input = np.array([[Year_Built,Year_Remod_Add,Total_Bsmt_SF,First_Flr_SF,Gr_Liv_Area,
                             Garage_Area,Overall_Qual,Garage_Cars]])
     prediction = model.predict(User_input)
     prediction = round(prediction[0],2)


  return render_template('index.html',prediction = prediction)

if __name__ == '__main__':
  app.run(debug =True)